name: Run tests

on:
  push:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: pip install tox
      - name: Run tests
        # As of now, running tox without environment runs the tests w.r.t the test matrix defined in
        # tox.ini.
        run: tox
